<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxxKZMe\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxxKZMe/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQxxKZMe.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQxxKZMe\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQxxKZMe\App_KernelProdContainer([
    'container.build_hash' => 'QxxKZMe',
    'container.build_id' => 'c786e505',
    'container.build_time' => 1580238805,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxxKZMe');
