index:
    path: /
    controller: App\Controller\Menu::index
Deconnexion:
    path: /Deconnexion/
    controller: App\Controller\Menu::Deconnexion
Check_Users:
    path: /Formulaire/Check_Users/
    controller: App\Controller\Menu::Check_Users
Login:
    path: /Formulaire/Login/
    controller: App\Controller\Menu::Login
Create_Formulaire:
    path: /Formulaire/Create/
    controller: App\Controller\Forms_Editing::Creation
Save_Img:
    path: /Formulaire/Save_Img/
    controller: App\Controller\Forms_Editing::Save_Img
Change_Forms:
    path: /Formulaire/Change_Forms/
    controller: App\Controller\Forms_Editing::Change_Forms
Delete_Forms:
    path: /Formulaire/Delete_Forms/
    controller: App\Controller\Forms_Editing::Delete_Forms
Restore_Forms:
    path: /Formulaire/Restore_Forms/
    controller: App\Controller\Forms_Editing::Restore_Forms
Read_Formulaire:
    path: /Formulaire/Read/{T_Slug}
    controller: App\Controller\Forms_Editing::Read
Change_Ligne:
    path: /Formulaire/Change_Ligne/
    controller: App\Controller\Forms_Editing::Change_Ligne
Create_Ligne:
    path: /Formulaire/Create_Ligne/
    controller: App\Controller\Forms_Editing::Create_Ligne
Delete_Ligne:
    path: /Formulaire/Delete_Ligne/
    controller: App\Controller\Forms_Editing::Delete_Ligne
Clone_Ligne:
    path: /Formulaire/Clone_Ligne/
    controller: App\Controller\Forms_Editing::Clone_Ligne
ChangelineOrder:
    path: /Formulaire/ChangelineOrder/
    controller: App\Controller\Forms_Editing::ChangelineOrder
ChangeInlineOrder:
    path: /Formulaire/ChangeInlineOrder/
    controller: App\Controller\Forms_Editing::ChangeInlineOrder
Create_InLigne:
    path: /Formulaire/Create_InLigne/
    controller: App\Controller\Forms_Editing::Create_InLigne
Change_InLigne:
    path: /Formulaire/Change_InLigne/
    controller: App\Controller\Forms_Editing::Change_InLigne
Delete_InLigne:
    path: /Formulaire/Delete_InLine/
    controller: App\Controller\Forms_Editing::Delete_InLine
Add_Groups_diffusion:
    path: /Formulaire/Add_Groups_diffusion/
    controller: App\Controller\Forms_Editing::Add_Groups_diffusion
Change_Groups_diffusion:
    path: /Formulaire/Change_Groups_diffusion/
    controller: App\Controller\Forms_Editing::Change_Groups_diffusion
Delete_Groups_diffusion:
    path: /Formulaire/Delete_Groups_diffusion/
    controller: App\Controller\Forms_Editing::Delete_Groups_diffusion
Valider_Forms:
    path: /Formulaire/Valider_Forms/
    controller: App\Controller\Forms_Editing::Valider_Forms
Unvalider_Forms:
    path: /Formulaire/Unvalider_Forms/
    controller: App\Controller\Forms_Editing::Unvalider_Forms
Response_Formulaire:
    path: /Formulaire/Reponse/{T_Slug_View}
    controller: App\Controller\Forms_Response::Form_Vue

#nom de la route:
#   path: lien url
#   controller: chemin controller :: nom fonction