index:
    path: /
    controller: App\Controller\Menu::index
Deconnexion:
    path: /Deconnexion/
    controller: App\Controller\Menu::Deconnexion
Create_Formulaire:
    path: /Formulaire/Create/
    controller: App\Controller\Forms_Editing::Creation
Read_Formulaire:
    path: /Formulaire/Read/{T_Slug}
    controller: App\Controller\Forms_Editing::Read

#nom de la route:
#   path: lien url
#   controller: chemin controller :: nom fonction