index:
    path: /
    controller: App\Controller\Menu::index
Deconnexion:
    path: /Deconnexion/
    controller: App\Controller\Menu::Deconnexion
Check_Users:
    path: /Formulaire/Check_Users/
    controller: App\Controller\Menu::Check_Users
Login:
    path: /Formulaire/Login/
    controller: App\Controller\Menu::Login
Create_Formulaire:
    path: /Formulaire/Create/
    controller: App\Controller\Forms_Editing::Creation
Read_Formulaire:
    path: /Formulaire/Read/{T_Slug}
    controller: App\Controller\Forms_Editing::Read
Change_Ligne:
    path: /Formulaire/Change_Ligne/
    controller: App\Controller\Forms_Editing::Change_Ligne
Create_Ligne:
    path: /Formulaire/Create_Ligne/
    controller: App\Controller\Forms_Editing::Create_Ligne
Delete_Ligne:
    path: /Formulaire/Delete_Ligne/
    controller: App\Controller\Forms_Editing::Delete_Ligne
ChangeInlineOrder:
    path: /Formulaire/ChangeInlineOrder/
    controller: App\Controller\Forms_Editing::ChangeInlineOrder
Create_InLigne:
    path: /Formulaire/Create_InLigne/
    controller: App\Controller\Forms_Editing::Create_InLigne
Change_InLigne:
    path: /Formulaire/Change_InLigne/
    controller: App\Controller\Forms_Editing::Change_InLigne
    
#nom de la route:
#   path: lien url
#   controller: chemin controller :: nom fonction