index:
    path: /
    controller: App\Controller\Menu::index
login:
    path: /Login/
    controller: App\Controller\Menu::Login
register:
    path: /Register/
    controller: App\Controller\Menu::Register
Create_Formulaire:
    path: /Formulaire/Create/
    controller: App\Controller\Forms_Editing::Creation
Read_Formulaire:
    path: /Formulaire/Read/{T_Slug}
    controller: App\Controller\Forms_Editing::Read

#nom de la route:
#   path: lien url
#   controller: chemin controller :: nom fonction