index:
    path: /
    controller: App\Controller\Menu::index
Deconnexion:
    path: /Deconnexion/
    controller: App\Controller\Menu::Deconnexion
Create_Formulaire:
    path: /Formulaire/Create/
    controller: App\Controller\Forms_Editing::Creation
Read_Formulaire:
    path: /Formulaire/Read/{T_Slug}
    controller: App\Controller\Forms_Editing::Read
Change_Ligne:
    path: /Formulaire/Change_Ligne/
    controller: App\Controller\Forms_Editing::Change_Ligne
Create_Ligne:
    path: /Formulaire/Create_Ligne/
    controller: App\Controller\Forms_Editing::Create_Ligne

#nom de la route:
#   path: lien url
#   controller: chemin controller :: nom fonction