#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\LuckyController::number
add_user:
    path: /adduser/
    controller: App\Controller\LuckyController::add_user