<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNE3osK2\App_KernelRpodDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNE3osK2/App_KernelRpodDebugContainer.php') {
    touch(__DIR__.'/ContainerNE3osK2.legacy');

    return;
}

if (!\class_exists(App_KernelRpodDebugContainer::class, false)) {
    \class_alias(\ContainerNE3osK2\App_KernelRpodDebugContainer::class, App_KernelRpodDebugContainer::class, false);
}

return new \ContainerNE3osK2\App_KernelRpodDebugContainer([
    'container.build_hash' => 'NE3osK2',
    'container.build_id' => 'f6355998',
    'container.build_time' => 1580238801,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNE3osK2');
