<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7XGuWfk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7XGuWfk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7XGuWfk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7XGuWfk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7XGuWfk\App_KernelDevDebugContainer([
    'container.build_hash' => '7XGuWfk',
    'container.build_id' => '40358331',
    'container.build_time' => 1580726637,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7XGuWfk');
