<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTZxowA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTZxowA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTZxowA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTZxowA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTZxowA\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTZxowA',
    'container.build_id' => 'aeb067ca',
    'container.build_time' => 1580735944,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTZxowA');
